pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.1.300'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration Release'
    majorVersion: 0
    minorVersion: 1
    patchVersion: 0

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
    